### ISSUE TITLE
Feature Transformations Discussion

### ISSUE THREAD

**Issue by jessie14** [UBC-MDS/DSCI_522_Spotify_Track_Popularity_Predictor#10]
These are the column types that I have identified along with transformations for each column type.
Does everyone agree with these transformations?

    #CountVectorizer
    text_features = "song" 

    #Impute with mean , StandardScaler
    numeric_features = ["spotify_track_duration_ms",
                        "danceability",
                        "energy",
                        "key",
                        "loudness",
                        "mode",
                        "speechiness",
                        "acousticness",
                        "instrumentalness",
                        "liveness",
                        "valence",
                        "tempo",
                        "time_signature"]

    #Onehotencoder
    binary_features = ["spotify_track_explicit"]

    #Impute with 'missing', Onehotencoder
    categorical_features = ["performer","spotify_genre"]

    #The following features are dropped because
             -"song_id" contains same info as "song"
             -"spotify_track_id" and  "spotify_track_preview_url" do not contain useful information
             -"spotify_track_album"  is less important the song name, and will be difficult to differentiate between words in album name or 
                song name if we use count vectorizer on both columns 
    drop_features = ["song_id","spotify_track_id","spotify_track_preview_url","spotify_track_album"]

    target = "spotify_track_popularity"

**Comment by Vikiano** [comment]
This looks good!

**Comment by rezam747** [comment]
We finally decide to do countvectorizer on the spotify_genre column:

numeric_features  = [
        'spotify_track_duration_ms',
        'danceability',
        'energy','key',
        'loudness','mode',
        'speechiness',
        'acousticness',
        'instrumentalness',
        'liveness',
        'valence',
        'tempo',
        'time_signature']
    categorical_features = ['performer']
    binary_features = ['spotify_track_explicit']
    drop_features = ['song_id', 'spotify_track_id', 'spotify_track_album']
