### ISSUE TITLE
RandomizedSearchCV Code Chunk 

### ISSUE THREAD

**Issue by jessie14** [UBC-MDS/DSCI_522_Spotify_Track_Popularity_Predictor#13]
Code chunk for RandomizedSearch
* Need to add argument random_search_results to docopt and main function

```
pipe = make_pipeline(preprocessor, Ridge())
    
    param_grid = {
    "ridge__alpha": loguniform(1e-3, 1e3),
    "columntransformer__countvectorizer__binary": np.array([True, False]),
    "columntransformer__countvectorizer__max_features": np.arange(1000, 10000, 1000),
  }

  random_search = RandomizedSearchCV(
      pipe, param_distributions=param_grid, n_jobs=-1, n_iter=10, cv=5
  )
  random_search.fit(X_train, y_train)
  random_search.best_params_
  
  random_search_results = pd.DataFrame(random_search.cv_results_)[
    [
        "mean_test_score",
        "param_ridge__alpha",
        "param_columntransformer__countvectorizer__max_features",
        "param_columntransformer__countvectorizer__binary""
        "rank_test_score",
    ]
  ].set_index("rank_test_score").sort_index()
  
  #random_search_results.to_csv(random_search_results, index = False)

```

**Comment by rezam747** [comment]
Thank you 👍 


param_grid = {
        "ridge__alpha": np.logspace(-3,2,6),
        "columntransformer__countvectorizer-1__binary": np.array([True, False]),
        "columntransformer__countvectorizer-1__max_features": np.arange(1000, 10000, 20000),
        "columntransformer__countvectorizer-2__binary": np.array([True, False]),
        "columntransformer__countvectorizer-2__max_features": np.arange(1000, 10000, 20000)
    }

    random_search = RandomizedSearchCV(
        pipe, param_distributions=param_grid, n_jobs=-1, n_iter=10, cv=5
    )
    
    random_search.fit(X_train, y_train)

    random_search_results = pd.DataFrame(random_search.cv_results_)[
        [
            "mean_test_score",
            "param_ridge__alpha",
            "param_columntransformer__countvectorizer-1__max_features",
            "param_columntransformer__countvectorizer-1__binary",
            "param_columntransformer__countvectorizer-2__max_features",
            "param_columntransformer__countvectorizer-2__binary",
            "rank_test_score",
        ]
    ].set_index("rank_test_score").sort_index()
  
    random_search_results.to_csv(f'{out_file}/best_hyperparameters.csv', index = False)
