### ISSUE TITLE
Test Set Eval Code Chunk (Using Best Model)

### ISSUE THREAD

**Issue by jessie14** [UBC-MDS/DSCI_522_Spotify_Track_Popularity_Predictor#15]
```
best_preprocessor = make_column_transformer(
    (make_pipeline(SimpleImputer(strategy='mean'),StandardScaler()),
                  numeric_features),
    (OneHotEncoder(sparse=False, drop="if_binary", dtype=int),binary_features),
    (make_pipeline(SimpleImputer(strategy="constant", fill_value="missing"),
                  OneHotEncoder(handle_unknown="ignore", sparse=False,categories=[most_frequent.index.values])),
                    categorical_features),
    (CountVectorizer(stop_words="english",
                    max_features=random_search.best_params_["columntransformer__countvectorizer__max_features"],
                    binary=random_search.best_params_["columntransformer__countvectorizer__binary"]),
                    text_features))
  
  best_pipe = make_pipeline(
    best_preprocessor,
    Ridge(
        alpha=random_search.best_params_["ridge__alpha"],
    )
  )

  best_pipe.fit(X_train, y_train)
  best_pipe.score(X_test, y_test)

```

**Comment by rezam747** [comment]
param_grid = {
        "ridge__alpha": np.logspace(-3,2,6),
        "columntransformer__countvectorizer-1__binary": np.array([True, False]),
        "columntransformer__countvectorizer-1__max_features": np.arange(1000, 10000, 20000),
        "columntransformer__countvectorizer-2__binary": np.array([True, False]),
        "columntransformer__countvectorizer-2__max_features": np.arange(1000, 10000, 20000)
    }

    random_search = RandomizedSearchCV(
        pipe, param_distributions=param_grid, n_jobs=-1, n_iter=10, cv=5
    )
    
    random_search.fit(X_train, y_train)

    random_search_results = pd.DataFrame(random_search.cv_results_)[
        [
            "mean_test_score",
            "param_ridge__alpha",
            "param_columntransformer__countvectorizer-1__max_features",
            "param_columntransformer__countvectorizer-1__binary",
            "param_columntransformer__countvectorizer-2__max_features",
            "param_columntransformer__countvectorizer-2__binary",
            "rank_test_score",
        ]
    ].set_index("rank_test_score").sort_index()
  

    try:
        random_search_results.to_csv(f'{out_file}/best_hyperparameters.csv', index = False)   # save the random_search results
    except:
        os.makedirs(os.path.dirname(f'{out_file}/best_hyperparameters.csv'))
        random_search_results.to_csv(f'{out_file}/best_hyperparameters.csv', index = False)
    

    #Evaluating on the test set 
    y_predicted = random_search.predict(X_test)
    df = pd.DataFrame({'y_test':y_test, 'y_predicted':y_predicted})

    plot = alt.Chart(df, title= "Predicted versus true Spotify popularities").mark_point(filled=True, clip=True).encode(
        alt.X('y_test', title='Predicted values of Spotify popularities'),
        alt.Y('y_predicted', title='True values of Spotify popularities', scale=alt.Scale(domain=(0, 100)))
    )
    plot_2 = plot + plot.mark_line(color = 'black').encode(
        alt.Y('y_test')
    )
