### ISSUE TITLE
Code for plot of model results

### ISSUE THREAD

**Issue by scarlqq** [UBC-MDS/DSCI_522_Spotify_Track_Popularity_Predictor#18]
import numpy as np
import pandas as pd
import altair as alt

y_test = np.random.randint(100, size=100)
y_predicted = np.random.randint(100, size=100)

df = pd.DataFrame({'y_test':y_test, 'y_predicted':y_predicted})
p = alt.Chart(df).mark_point(filled=True).encode(
    alt.X('y_test', title='Predicted values of Spotify popularities'),
    alt.Y('y_predicted', title='True values of Spotify popularities')
)

p2 = p+p.transform_regression('y_test', 'y_predicted').mark_line()
p2.save('test.png')

**Comment by rezam747** [comment]
Thanks.
