### ISSUE TITLE
Submission check list

### ISSUE THREAD

**Issue by scarlqq** [UBC-MDS/DSCI_522_Spotify_Track_Popularity_Predictor#8]
1. A link in README.md, point to eda.pdf
2. Create a release named "0.0.1"
3. The URL needs to be included in submission:
(1) the URL of public project’s repository
(2) the URL to the release "0.0.1"

**Comment by rezam747** [comment]
1. Jessie fixed the ReadME.md eda.pdf link
2. I created the "0.0.1" release.
3. Submitted these in can links on Canvas :
 The URL of public project’s repository: https://github.com/UBC-MDS/DSCI_522_Spotify_Track_Popularity_Predictor (Links to an external site.)

 The URL to the release "0.0.1" : https://github.com/UBC-MDS/DSCI_522_Spotify_Track_Popularity_Predictor/releases/tag/0.0.1 (Links to an external site.)

Team work contract: https://docs.google.com/document/d/1podJT4PPjsWs2Jhel1-DORRFVqaPG068Y5_shWa5zgY/edit

**Comment by jessie14** [comment]
Milestone 1 Deliverables successfully submitted.
